// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _11_TablePerHierarchy_TPH_.Context;

#nullable disable

namespace _11_TablePerHierarchy_TPH_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221122161315_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("_11_TablePerHierarchy_TPH_.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("_11_TablePerHierarchy_TPH_.Entities.Customer", b =>
                {
                    b.HasBaseType("_11_TablePerHierarchy_TPH_.Entities.Person");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("_11_TablePerHierarchy_TPH_.Entities.Employee", b =>
                {
                    b.HasBaseType("_11_TablePerHierarchy_TPH_.Entities.Person");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("_11_TablePerHierarchy_TPH_.Entities.Technician", b =>
                {
                    b.HasBaseType("_11_TablePerHierarchy_TPH_.Entities.Employee");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Technician");
                });
#pragma warning restore 612, 618
        }
    }
}
