// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_SeedData.Context;

#nullable disable

namespace _10_SeedData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("_10_SeedData.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "www.myblog.com"
                        },
                        new
                        {
                            Id = 2,
                            Url = "www.ourblog.com"
                        });
                });

            modelBuilder.Entity("_10_SeedData.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            Content = "This is first content",
                            Title = "This is first title"
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            Content = "This is second content",
                            Title = "This is second title"
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            Content = "This is third content",
                            Title = "This is third title"
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 2,
                            Content = "This is fourth content",
                            Title = "This is fourth title"
                        });
                });

            modelBuilder.Entity("_10_SeedData.Entities.Post", b =>
                {
                    b.HasOne("_10_SeedData.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("_10_SeedData.Entities.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
