// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _12_TablePerType_TPT_.Context;

#nullable disable

namespace _12_TablePerType_TPT_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221126130631_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Customer", b =>
                {
                    b.HasBaseType("_12_TablePerType_TPT_.Entities.Person");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Employee", b =>
                {
                    b.HasBaseType("_12_TablePerType_TPT_.Entities.Person");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Technician", b =>
                {
                    b.HasBaseType("_12_TablePerType_TPT_.Entities.Employee");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.ToTable("Tecnicians", (string)null);
                });

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Customer", b =>
                {
                    b.HasOne("_12_TablePerType_TPT_.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("_12_TablePerType_TPT_.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Employee", b =>
                {
                    b.HasOne("_12_TablePerType_TPT_.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("_12_TablePerType_TPT_.Entities.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_12_TablePerType_TPT_.Entities.Technician", b =>
                {
                    b.HasOne("_12_TablePerType_TPT_.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("_12_TablePerType_TPT_.Entities.Technician", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
